Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,16 +32,20 @@ jobs:
           # Extract Version
           version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' Directory.Build.props)
 
+          if [ -z "$version" -a -z "$assemblyVersion" ]; then
+            echo "::error::Unable to extract the project version."
+            exit 1
+          fi
 
           # If Version not found, use AssemblyVersion
           if [ -z "$version" ]; then
             version="$(assemblyVersion)"
           fi
 
-          if [ ! -z "$assemblyVersion" ]; then
-            # Replace $(AssemblyVersion) in version with the value of assemblyVersion
-            version=$(echo "$version" | sed "s/\$(AssemblyVersion)/$assemblyVersion/g")
-          fi
+          #if [ ! -z "$assemblyVersion" ]; then
+          #  # Replace $(AssemblyVersion) in version with the value of assemblyVersion
+          #  version=$(echo "$version" | sed "s/\$(AssemblyVersion)/$assemblyVersion/g")
+          #fi
 
           # Ensure version is valid
           if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.?[0-9]+)?)?$ ]]; then
@@ -49,9 +53,9 @@ jobs:
             exit 1
           fi
 
-          echo "Version=$version" >> $GITHUB_ENV
           echo "Extracted and Resolved AssemblyVersion: $assemblyVersion"
           echo "Extracted and Resolved Version: $version"
+          echo "Version=$version" >> $GITHUB_ENV
 
       # 📝 Parse changelog for the version
       - name: 📝 Parse changelog
